export const Restaurants = [
  {
    title: "The Ora Cafe",
    categories: "North Indian, Beverages",
    rating: "4.0",
    delivery_time: "25",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rh1kpotnhdlbfruwgn2c",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Sanjay Colony",
  },
  {
    title: "Mirchi Restaurant",
    categories: "North Indian",
    rating: "3.9",
    delivery_time: "20",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/povypukzcottzmhmy4fy",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Hot Pizza",
    categories: "Italian, Pizzas",
    rating: "3.9",
    delivery_time: "23",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/onrussybboydf7hpidkr",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Bholenath Pizza Centre",
    categories: "Fast Food, Pizzas",
    rating: "4.2",
    delivery_time: "35",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/gyfr4kyppruesvoecmdl",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Kanha ji daal bati",
    categories: "Indian",
    rating: "4.2",
    delivery_time: "26",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xary7u2zjewtkwpnjyll",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Asha Restaurant",
    categories: "North Indian, South Indian, Chinese, Snacks",
    rating: "4.5",
    delivery_time: "22",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vczeztxo1wpk9pqxiucq",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Eating Seating",
    categories: "Fast Food",
    rating: "3.9",
    delivery_time: "22",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fn3rq0hstxf30n5wdrbv",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Mahalaxmi Bakers",
    categories: "North Indian, Desserts",
    rating: "4.0",
    delivery_time: "17",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/r0q2nzue0zgjl8xd2bzv",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Sonu Patties",
    categories: "American, Fast Food, Pizzas, Snacks, Beverages",
    rating: "3.6",
    delivery_time: "21",
    price: "149",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dmwpvksmmgezvmrdxrvm",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Hangout",
    categories: "Chinese, South Indian, North Indian, Continental, Fast Food",
    rating: "3.7",
    delivery_time: "20",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/l3clh7uogyqu8b4igg9r",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Angeethi Restaurant (Hotel Ashoka Residency)",
    categories: "Desserts, Thai",
    rating: "3.1",
    delivery_time: "24",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vejmtuy9txuwelm0xeba",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Shastri Nagar",
  },
  {
    title: "Mateshwari Falhari Center",
    categories: "Snacks, Fast Food",
    rating: "4.5",
    delivery_time: "18",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xdhojkajxdugzfwi0wdc",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Hotel Raza",
    categories: "Mughlai",
    rating: "3.2",
    delivery_time: "20",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bqmuzk3g1kqyadrqgcxb",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Old Bhilwara",
  },
  {
    title: "Bikaner Family Restaurant",
    categories: "North Indian",
    rating: "3.2",
    delivery_time: "23",
    price: "220",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/jecyl9m4vuwbolvrorua",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "City Hart momos",
    categories: "Snacks, Fast Food",
    rating: "4.5",
    delivery_time: "29",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/aoiedyp0xbdjphnflmwt",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "INOX",
    categories: "Fast Food",
    rating: "4.5",
    delivery_time: "24",
    price: "400",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/b1fv0tsksuat0z34pmrp",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Gandhi Nagar",
  },
  {
    title: "SM Maggi n pasta",
    categories: "Fast Food, Pastas",
    rating: "4.5",
    delivery_time: "23",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/txxyx0ehqvmznwavmjtz",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, R K Colony",
  },
  {
    title: "Jodhpur Sweets",
    categories: "Desserts, Snacks",
    rating: "4.1",
    delivery_time: "16",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/nxmmra9fydoaqprkrtqv",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Chalta Firta Restaurant",
    categories: "North Indian, Rajasthani",
    rating: "4.5",
    delivery_time: "31",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xg0vcdztyvdxjbxkswsf",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "SS Chowmein & Manchurian",
    categories: "North Indian",
    rating: "3.6",
    delivery_time: "22",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/wy7bjujpqeo9bxl8da8d",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Chawla Chicken",
    categories: "Mughlai, Punjabi",
    rating: "3.3",
    delivery_time: "24",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/wexrils7tj2dkiifbfv0",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Nehru Road, Sanjay Colony",
  },
  {
    title: "Baskin Robbins",
    categories: "Desserts",
    rating: "4.0",
    delivery_time: "20",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/l8u5sjmpqgrrt1wixdha",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Saffron The Family Restaurant",
    categories: "North Indian",
    rating: "3.5",
    delivery_time: "21",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/p31bjtoghmc6amfytqs7",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, RAJASTHAN, Bhopal Ganj",
  },
  {
    title: "Aloo Bada Centre",
    categories: "Snacks",
    rating: "4.5",
    delivery_time: "25",
    price: "50",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vacqsxxsu84u6w38fg74",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shyam Nagar",
  },
  {
    title: "Bikaner Bhojnalaya",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "32",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/stmjaayn3x065rpdilgc",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Pur Road",
  },
  {
    title: "O-zone Cafe",
    categories: "Pizzas, Fast Food, Snacks, Chinese, Beverages",
    rating: "4.5",
    delivery_time: "25",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vacqsxxsu84u6w38fg74",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Suruchi Restaurant",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "27",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/nl2p1o5m6gvwvx0nfgck",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Ajmer Choraha",
  },
  {
    title: "Crave Nation",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "22",
    price: "350",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dqic0ecgabor01aggdwt",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shubash Nager",
  },
  {
    title: "The Brij Kanha restaurant",
    categories: "Indian",
    rating: "4.5",
    delivery_time: "27",
    price: "500",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ju2jsn27fbqbpft50u6q",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "The Roll Junction",
    categories: "Fast Food, Mexican, North Indian",
    rating: "3.3",
    delivery_time: "26",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bqbosireq9q5g5lv4eu6",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Bhagat Singh Colony",
  },
  {
    title: "The Brown Sugar Bakery",
    categories: "Desserts, Bakery",
    rating: "4.4",
    delivery_time: "25",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fhupbdldqbjbb3bhq8ik",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Delhi Thali Restaurant",
    categories: "North Indian, Desserts",
    rating: "3.7",
    delivery_time: "19",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ss6esa4ktlcnbwy9xdje",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Hotel Apsara",
    categories: "North Indian",
    rating: "3.2",
    delivery_time: "24",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ax3hkr2wr21qy7otxqss",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Shree Sanwariya Restaurant",
    categories: "North Indian, Rajasthani",
    rating: "4.2",
    delivery_time: "27",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/akbnfuabaonpdvrmagcb",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "Score board sports cafe",
    categories: "Fast Food, Italian, North Indian, Pizzas",
    rating: "3.1",
    delivery_time: "25",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/kswi0kmh2cicxl7a7fla",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Old Bhilwara",
  },
  {
    title: "Mami ka pizza",
    categories: "Indian",
    rating: "3.0",
    delivery_time: "25",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/utfuoomhsc1zqoaddl8e",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "Apsara patties and pizza",
    categories: "Pizzas, Fast Food, Beverages",
    rating: "4.5",
    delivery_time: "24",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/e1pqshqyzumuwmmgn0qo",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Gandhi Nagar",
  },
  {
    title: "Harichhaya Garden restaurant",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "27",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/aj8uo8zfarfme9jzhaci",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Roll express",
    categories: "North Indian, Chinese, Snacks",
    rating: "4.1",
    delivery_time: "27",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bj8dju5wf8h0wikjrr11",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, R K Colony",
  },
  {
    title: "Gourmet Ice Cream Cakes by Baskin Robbins",
    categories: "Desserts, Ice Cream, Bakery",
    rating: "4.5",
    delivery_time: "29",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/py1nqakqmyioblax02yj",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Nehru Road, Sanjay Colony",
  },
  {
    title: "Bobbys cafe",
    categories: "Fast Food",
    rating: "4.5",
    delivery_time: "26",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/qeio1yxsmrgda5en1p10",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, RAJASTHAN, Bhopal Ganj",
  },
  {
    title: "Eva s Eatery",
    categories: "Fast Food, Beverages",
    rating: "4.5",
    delivery_time: "25",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/t20gtkpmkxusbr2ovzpg",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "SN Pizza",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "31",
    price: "150",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yrykqhbkcci76vuwcysw",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shyam Nagar",
  },
  {
    title: "The Storix cafe",
    categories: "Italian, Continental, Beverages",
    rating: "4.5",
    delivery_time: "30",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vgfv2xsmjvxbj4rizngu",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Pur Road",
  },
  {
    title: "TEA & TALKS",
    categories: "Beverages, Snacks, Pizzas",
    rating: "4.5",
    delivery_time: "26",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rnupdiyo6o09n196kiib",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Ajmer Choraha",
  },
  {
    title: "Shree Sanwariya Bhojnalaya",
    categories: "Indian, Rajasthani",
    rating: "4.5",
    delivery_time: "34",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/cwfw3nw1coisgsu8k17n",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Sip & Gossip Cafe",
    categories: "North Indian",
    rating: "3.9",
    delivery_time: "31",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rgwsbhxhaf5ns57z29v1",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shubash Nager",
  },
  {
    title: "Ministry of Pastry Bakehouse",
    categories: "Bakery, Desserts, Snacks, Beverages",
    rating: "4.5",
    delivery_time: "25",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/n0hq2htqutjec6fe2mjj",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Bhagat Singh Colony",
  },
  {
    title: "Hotel Tulip continental",
    categories:
      "Chinese, South Indian, North Indian, Continental, American, Desserts, Fast Food,...",
    rating: "4.5",
    delivery_time: "31",
    price: "500",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/agrvbjh6y7ydi7ugp2ow",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "The Mojo Cake N Bake",
    categories: "Fast Food, Chinese, Beverages",
    rating: "4.5",
    delivery_time: "33",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/j6agxyn7x724sq7w6e2j",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Coffee Culture",
    categories:
      "Pizzas, Pastas, Italian, Indian, American, Chinese, Fast Food, Mexican, Beverage...",
    rating: "4.5",
    delivery_time: "27",
    price: "350",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rmldmdjbrtdn5ugjzi1c",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Blue Umbrella Bakers",
    categories: "Bakery, Desserts",
    rating: "4.5",
    delivery_time: "27",
    price: "400",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/qwpuyymmguzi5kfqxymv",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Hari Sewa Bakers",
    categories: "Bakery",
    rating: "4.5",
    delivery_time: "33",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dfm62dmaras86pzn8mdr",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Old Bhilwara",
  },
  {
    title: "Surprise India",
    categories: "Bakery",
    rating: "4.5",
    delivery_time: "32",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ew8npb9jay2qcbjll5ff",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "Shreenath Pav Bahji",
    categories: "North Indian, Fast Food",
    rating: "4.5",
    delivery_time: "24",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ikihp6dkkwf1zgijj56f",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Balaji Fast Food",
    categories: "Fast Food",
    rating: "4.5",
    delivery_time: "32",
    price: "150",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fcucdkclujxlwh7q3ntt",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Gandhi Nagar",
  },
  {
    title: "Domino's Pizza",
    categories: "Pizzas",
    rating: "3.5",
    delivery_time: "30",
    price: "400",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vomknfcgepzvg2nh6sr4",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, R K Colony",
  },
  {
    title: "Sukhwal Fast Food",
    categories: "Fast Food",
    rating: "3.6",
    delivery_time: "25",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ufk6hwdva4ygf4ywvddl",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Nehru Road, Sanjay Colony",
  },
  {
    title: "Seven Stone",
    categories: "Continental, Fast Food, North Indian",
    rating: "4.5",
    delivery_time: "34",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/kuyej4p4605f9pz927m4",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Dev Restaurant",
    categories: "North Indian",
    rating: "3.6",
    delivery_time: "30",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dsckhsggcpekxosqih7w",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, RAJASTHAN, Bhopal Ganj",
  },
  {
    title: "Street Wok",
    categories: "Fast Food",
    rating: "4.5",
    delivery_time: "27",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ekowsaxassuzm779t451",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shyam Nagar",
  },
  {
    title: "Love bird pizza",
    categories: "Continental",
    rating: "4.0",
    delivery_time: "25",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yrykqhbkcci76vuwcysw",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Shree Ram Pizza Corner",
    categories: "Ice Cream, Desserts",
    rating: "4.5",
    delivery_time: "34",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vtasj2fb8jinkwwordnm",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Pur Road",
  },
  {
    title: "Chef's secret...",
    categories: "Indian, Chinese, Beverages",
    rating: "4.5",
    delivery_time: "27",
    price: "150",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pdnotve8mehn9mn3jnrd",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Ajmer Choraha",
  },
  {
    title: "Chicken Point",
    categories: "Indian, Biryani, Beverages",
    rating: "4.5",
    delivery_time: "27",
    price: "220",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/lt40imc7bdvpqbjl1erh",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shubash Nager",
  },
  {
    title: "Rasoda",
    categories: "North Indian, Chinese, Snacks",
    rating: "4.1",
    delivery_time: "28",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/d8pqyjprjyp6whgjgzo0",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Bhagat Singh Colony",
  },
  {
    title: "H3 Cafe - By Dosa Planet",
    categories: "South Indian, Beverages",
    rating: "3.5",
    delivery_time: "29",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/f74rcuwveboq3hxtghjc",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Curry by kilo by Ora Foods",
    categories: "North Indian, Snacks, Beverages",
    rating: "4.5",
    delivery_time: "28",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/qpmnaxmnsblm966jpxwr",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Pink plate",
    categories: "Indian, Continental, Beverages",
    rating: "4.5",
    delivery_time: "33",
    price: "350",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xltqkrjbtljpbqmacv8l",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "SM Maggi",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "26",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/jfckf4ixsauzlqtdjiwk",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Radhey Kachori Center",
    categories: "North Indian, Sweets, Snacks",
    rating: "4.5",
    delivery_time: "25",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rjlyrjx6murpb741uzvn",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Hotel Radiance",
    categories: "North Indian, Chinese, Pizzas",
    rating: "4.5",
    delivery_time: "32",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ubfmqsoz1qmp64baoqkk",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Old Bhilwara",
  },
  {
    title: "303 The Royal Recipes",
    categories: "South Indian, Indian, Beverages",
    rating: "4.5",
    delivery_time: "29",
    price: "600",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hqxzzstw2uw0vsb4azwq",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "Lovish cake n bake",
    categories: "Bakery",
    rating: "4.5",
    delivery_time: "32",
    price: "400",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fub39s2im3lyjp9qur9g",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Gandhi Nagar",
  },
  {
    title: "Mateshwari falhari",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "32",
    price: "100",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pdp4pvytli0i2xcsx7gp",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, R K Colony",
  },
  {
    title: "Chetna Pizza",
    categories: "Pizzas, Fast Food",
    rating: "4.5",
    delivery_time: "35",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xhgulwdzwylfecwoon4e",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Fumes & Flames",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "26",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/gjaghzrrfivu7nadknhy",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Nehru Road, Sanjay Colony",
  },
  {
    title: "Salty house",
    categories: "North Indian, Fast Food",
    rating: "4.5",
    delivery_time: "28",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yijkdvg0sh84xqcdxnyi",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, RAJASTHAN, Bhopal Ganj",
  },
  {
    title: "House of masala",
    categories: "Oriental, Continental",
    rating: "4.5",
    delivery_time: "32",
    price: "350",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/w05wavfpx63pbgssdcpl",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Masala nonveg restaurant",
    categories: "Indian",
    rating: "4.5",
    delivery_time: "30",
    price: "350",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pjzdckenmvaasiqwvbhm",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "B12 Garden Restaurant",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "29",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hsctkh7zgrzkvk5ma1yr",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shyam Nagar",
  },
  {
    title: "Cam`s Kitchen",
    categories: "Indian",
    rating: "4.5",
    delivery_time: "30",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/o2sygqkadp67l5urgavr",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Pur Road",
  },
  {
    title: "THE CHAWLA'S BAKERY",
    categories: "Bakery, Fast Food, Pizzas, Desserts, Beverages",
    rating: "4.5",
    delivery_time: "24",
    price: "300",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yi5erbrprwg2wu0i48ot",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Ajmer Choraha",
  },
  {
    title: "Firangi Club",
    categories: "Continental, North Indian",
    rating: "4.5",
    delivery_time: "31",
    price: "400",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/nxxt3aogxodktcf3sol5",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "BHILWARA, Shubash Nager",
  },
  {
    title: "OM SHREE SAI KRIPA",
    categories: "Chinese, Indian, Juices",
    rating: "4.5",
    delivery_time: "32",
    price: "200",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bzzkxlrsgtgtohwxxkbx",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Tikka N Talk",
    categories: "North Indian",
    rating: "4.5",
    delivery_time: "39",
    price: "250",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/b0h47qxxix9btal3jqoo",
    offer_status: true,
    offer: 60,
    coupon_code: "STEALDEAL",
    address: "Bhilwara, Bhopal Ganj",
  },
];
